[package]
name = "json-script"
version = "0.1.0"
edition = "2021"

[dependencies]
json-script-macro = { path = "../json-script-macro" }
skyline_smash = { git = "https://github.com/blu-dev/skyline-smash", features = ["weak_l2cvalue"] }
bitflags = "2"
