[package]
name = "proc-hitbox"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-hitbox-macro = { path = "../proc-hitbox-macro" }
skyline_smash = { git = "https://github.com/blu-dev/skyline-smash", features = ["weak_l2cvalue"] }
bitflags = "2"
